consul:
  image: sequenceiq/consul:v0.5.0
  environment:
    # TODO no way to expand shell env variables
    - BRIDGE_IP=172.17.42.1
  command: -server -bootstrap -advertise 172.17.42.1
  hostname: consul1
  ports:
    - 0.0.0.0:53:53/udp
    - 0.0.0.0:8400:8400
    - 0.0.0.0:8500:8500


registrator:
  image: gliderlabs/registrator
  command: consul://172.17.42.1:8500
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock


haproxy:
  image: aperepel/consul-template-balancer
  ports:
    - 80:80
  volumes:
    - .:/consul-template
